apiVersion: v1
kind: Service
metadata:
  name: mellat-headless
  namespace: mellat
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: nginx-headless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80