apiVersion: v1
kind: Service
metadata:
  name: mellat-np
  namespace: mellat
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80