apiVersion: v1
kind: Service
metadata:
  name: mellat-lb
  namespace: mellat
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80